#!/bin/bash
config='.elasticbeanstalk/config.yml'
war=$(ls -t target/scala-*/*.war | head -1)
[ -z "$war" ] && exit 1
if [ $(grep -cE '^  artifact: ' $config) -eq 0 ]; then
    cat >> $config <<EOH
deploy:
  artifact: $war
EOH
else
  perl -pe "s|^  artifact: .*|  artifact: $war|" -i.bk $config
fi

echo "artifact set to $war"
